<?php
require_once("statements/schema/MySQLSchemaUseStatement.php");
require_once("statements/server/MySQLServerExplainStatement.php");
require_once("statements/server/MySQLServerGetProcessesStatement.php");
require_once("statements/server/MySQLServerKillProcessStatement.php");
require_once("statements/server/MySQLServerSetStatement.php");
require_once("statements/table/MySQLTableAlterStatement.php");
require_once("statements/table/MySQLTableCreateStatement.php");
require_once("statements/table/MySQLTableDeleteStatement.php");
require_once("statements/table/MySQLTableInsertStatement.php");
require_once("statements/table/MySQLTableInsertSelectStatement.php");
require_once("statements/table/MySQLTableRenameStatement.php");
require_once("statements/table/MySQLTableReplaceStatement.php");
require_once("statements/table/MySQLTableReplaceSelectStatement.php");
require_once("statements/table/MySQLTableUpdateStatement.php");

//require_once("constants/MySQLWhereClause.php");
//require_once("constants/MySQLWhereGroupClause.php");
//require_once("constants/MySQLSetOperator.php");